apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev-project
  namespace: argocd
spec:
  description: Dev environment - relaxed
  sourceRepos:
    - https://github.com/mfahad544/gitops-demo.git
  destinations:
    - namespace: myapp-dev
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
