apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-demo
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: redis-demo
  template:
    metadata:
      labels:
        app: redis-demo
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
