apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  progressDeadlineSeconds: 30
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
  progressDeadlineSeconds: 30
      containers:
        - name: postgres
          image: postgres:broken-tag
          env:
            - name: POSTGRES_PASSWORD
              value: demopassword
            - name: POSTGRES_DB
              value: demodb
          ports:
            - containerPort: 5432
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 5
            periodSeconds: 5
